import Link from 'next/link';
import {dbConfigured,dbSelect} from '@/lib/supabase-rest';
import {candidateQuery,UFS,OFFICES} from '@/lib/candidate-query';
import DataNotice from '@/components/DataNotice';
import type {Candidate} from '@/lib/candidates';
export const dynamic='force-dynamic';
export default async function Page({searchParams}:{searchParams:Promise<{uf?:string;cargo?:string;q?:string;page?:string}>}){
 const sp=await searchParams,uf=(sp.uf||'').toUpperCase(),cargo=sp.cargo||'',q=(sp.q||'').slice(0,80);
 let rows:Candidate[]=[],failed=false,invalid=false,page=1,size=24;
 try{const parsed=candidateQuery({uf,office:cargo,q,page:Number(sp.page)||1});page=parsed.page;size=parsed.size;if(dbConfigured){try{rows=await dbSelect('candidates',parsed.query);}catch{failed=true;}}}catch{invalid=true;}
 const more=rows.length>size,candidates=rows.slice(0,size);
 const pageUrl=(n:number)=>`/candidaturas?${new URLSearchParams({uf,cargo,q,page:String(n)})}`;
 return <main className="page"><div className="eyebrow">ELEIÇÕES 2026 • DADOS RASTREÁVEIS</div><h1>Candidaturas</h1><p className="lead">Consulte os registros importados da fonte oficial. A situação de uma candidatura pode mudar após a última coleta.</p><form className="filters"><label>Nome na urna<input name="q" defaultValue={q} maxLength={80} placeholder="Buscar candidatura"/></label><label>UF<select name="uf" defaultValue={uf}><option value="">Todas</option>{UFS.map(x=><option key={x} value={x}>{x==='BR'?'BR — Presidência':x}</option>)}</select></label><label>Cargo<select name="cargo" defaultValue={cargo}><option value="">Todos</option>{OFFICES.map(x=><option key={x}>{x}</option>)}</select></label><button className="btn">Filtrar</button><Link className="btn secondary" href="/candidaturas">Limpar</Link></form>{invalid?<div className="note" role="alert">UF inválida. Selecione uma opção da lista.</div>:!dbConfigured?<DataNotice state="unconfigured"/>:failed?<DataNotice state="error"/>:!candidates.length?<DataNotice state="empty"/>:<><p className="stamp">Página {page} · {candidates.length} registros nesta página</p><div className="candidateGrid">{candidates.map(c=><Link className="candidateCard" href={`/candidaturas/${encodeURIComponent(c.id)}`} key={c.id}><div><span className="office">{c.office}</span><h2>{c.ballot_name}</h2><p>{c.full_name}</p></div><div className="candidateMeta"><b>{c.number||'—'} • {c.party||'—'}</b><span>{c.uf||c.scope}</span><span className="statusPill">{c.registration_status||'Situação não informada'}</span><small>Coleta: {c.source_updated_at?new Date(c.source_updated_at).toLocaleDateString('pt-BR',{timeZone:'America/Recife'}):'não informada'}</small></div></Link>)}</div></>}{dbConfigured&&!failed&&!invalid&&<nav className="actions" aria-label="Paginação">{page>1&&<Link className="btn secondary" href={pageUrl(page-1)}>Anterior</Link>}{more&&<Link className="btn" href={pageUrl(page+1)}>Próxima</Link>}</nav>}<p className="stamp"><a href="https://dadosabertos.tse.jus.br/dataset/candidatos-2026" target="_blank" rel="noreferrer">Consultar a fonte oficial do TSE</a></p></main>;
}
