import Link from 'next/link';
import {dbConfigured,dbSelect} from '@/lib/supabase-rest';
import DataNotice from '@/components/DataNotice';
export const dynamic='force-dynamic';
export default async function Page({searchParams}:{searchParams:Promise<{page?:string}>}){
 const sp=await searchParams,page=Math.min(10000,Math.max(1,Math.trunc(Number(sp.page)||1)));let failed=false;
 const rows:any[]=dbConfigured?await dbSelect('polls',`select=*&order=field_end.desc,id.asc&limit=25&offset=${(page-1)*24}`).catch(()=>{failed=true;return []}):[];
 return <main className="page"><div className="eyebrow">PESQUISAS ELEITORAIS</div><h1>Pesquisas no contexto</h1><p className="lead">Registros oficiais de pesquisas, instituto, período de campo, amostra e metodologia. O cadastro de uma pesquisa não contém necessariamente seus resultados eleitorais.</p>{!dbConfigured?<DataNotice state="unconfigured"/>:failed?<DataNotice state="error"/>:!rows.length?<DataNotice state="empty"/>:<><p>Página {page}</p><div className="grid">{rows.slice(0,24).map(p=><article className="card" key={p.id}><h2>{p.institute||'Instituto não informado'}</h2><p><b>Registro:</b> {p.registry_number||'—'}</p><p><b>Campo:</b> {p.field_start||'—'} a {p.field_end||'—'}</p><p><b>Amostra:</b> {p.sample_size??'não informada'}</p><p><b>Abrangência:</b> {p.scope||'—'}</p><p>Margem e confiança: consultar metodologia; não inferidas automaticamente.</p>{p.methodology&&<details><summary>Metodologia declarada</summary><p>{p.methodology}</p></details>}{p.sampling_plan&&<details><summary>Plano amostral</summary><p>{p.sampling_plan}</p></details>}<p><a href={p.source_url||'https://dadosabertos.tse.jus.br/dataset/pesquisas-eleitorais-2026'} target="_blank" rel="noreferrer">Arquivo oficial do TSE</a></p><p className="stamp">Coleta: {p.collected_at?new Date(p.collected_at).toLocaleString('pt-BR'):'não informada'}</p></article>)}</div></>}{dbConfigured&&!failed&&<nav className="actions" aria-label="Paginação">{page>1&&<Link className="btn secondary" href={`/pesquisas?page=${page-1}`}>Anterior</Link>}{rows.length>24&&<Link className="btn" href={`/pesquisas?page=${page+1}`}>Próxima</Link>}</nav>}</main>;
}
