import {dbConfigured,dbSelect} from '@/lib/supabase-rest';
import DataNotice from '@/components/DataNotice';
export const dynamic='force-dynamic';
export default async function Page({searchParams}:{searchParams:Promise<{a?:string;b?:string}>}){
 const {a='',b=''}=await searchParams;let candidates:any[]=[],proposals:any[]=[],failed=false;
 if(dbConfigured){try{candidates=await dbSelect('candidates','select=id,ballot_name,office,uf&active=eq.true&office=in.(PRESIDENTE,GOVERNADOR)&order=ballot_name.asc&limit=500');const ids=[a,b].filter(id=>candidates.some(c=>c.id===id));if(ids.length)proposals=await dbSelect('proposals',`candidate_id=in.(${ids.map(encodeURIComponent).join(',')})&reviewed_at=not.is.null&order=topic.asc&limit=500`);}catch{failed=true;}}
 const selected=[a,b].map(id=>candidates.find(c=>c.id===id));const comparable=selected.every(Boolean)&&a!==b&&selected[0].office===selected[1].office&&selected[0].uf===selected[1].uf;
 const topics=[...new Set(proposals.map(p=>p.topic))];
 return <main className="page"><div className="eyebrow">DOCUMENTOS OFICIAIS</div><h1>Comparador de propostas</h1><p className="lead">Compare trechos revisados de planos de governo para o mesmo cargo e circunscrição. Cada trecho mantém o documento e a página de origem, sem pontuação de candidaturas.</p>{!dbConfigured?<DataNotice state="unconfigured"/>:failed?<DataNotice state="error"/>:<><form className="filters">{(['a','b'] as const).map((name,i)=><label key={name}>Candidatura {i+1}<select name={name} defaultValue={i===0?a:b} required><option value="">Selecione</option>{candidates.map(c=><option key={c.id} value={c.id}>{c.ballot_name} · {c.office} · {c.uf}</option>)}</select></label>)}<button className="btn">Comparar</button></form>{a&&b&&!comparable?<div className="note">Selecione duas candidaturas diferentes para o mesmo cargo e UF.</div>:comparable?topics.length?<div className="comparison"><table><caption>Trechos documentados por tema</caption><thead><tr><th>Tema</th>{selected.map(c=><th key={c.id}>{c.ballot_name}</th>)}</tr></thead><tbody>{topics.map(topic=><tr key={topic}><th scope="row">{topic}</th>{selected.map(c=>{const items=proposals.filter(p=>p.candidate_id===c.id&&p.topic===topic);return <td key={c.id}>{items.length?items.map(p=><article key={p.id}><blockquote>{p.excerpt}</blockquote><a href={/^https:\/\//.test(p.document_url)?p.document_url:undefined} target="_blank" rel="noreferrer">Documento original · página {p.page_number??'não informada'}</a><p className="stamp">Revisado em {new Date(p.reviewed_at).toLocaleDateString('pt-BR')}</p></article>):'Nenhum trecho revisado disponível neste tema.'}</td>})}</tr>)}</tbody></table></div>:<DataNotice state="empty"/>:<p>Selecione as candidaturas para consultar os trechos disponíveis.</p>}</>}<div className="note">A extração e a revisão dos planos de governo ainda precisam alimentar esta base. Ausência de trecho não significa ausência de proposta.</div></main>;
}
